# Expand this registry as needed. The resolver is deliberately data-driven.
PAKISTAN_LOCATIONS = {
    "Islamabad": {"province": "Islamabad Capital Territory", "district": "Islamabad", "city": "Islamabad"},
    "Lahore": {"province": "Punjab", "district": "Lahore", "city": "Lahore"},
    "Rawalpindi": {"province": "Punjab", "district": "Rawalpindi", "city": "Rawalpindi"},
    "Faisalabad": {"province": "Punjab", "district": "Faisalabad", "city": "Faisalabad"},
    "Multan": {"province": "Punjab", "district": "Multan", "city": "Multan"},
    "Gujranwala": {"province": "Punjab", "district": "Gujranwala", "city": "Gujranwala"},
    "Sialkot": {"province": "Punjab", "district": "Sialkot", "city": "Sialkot"},
    "Gujrat": {"province": "Punjab", "district": "Gujrat", "city": "Gujrat"},
    "Sahiwal": {"province": "Punjab", "district": "Sahiwal", "city": "Sahiwal"},
    "Okara": {"province": "Punjab", "district": "Okara", "city": "Okara"},
    "Jhelum": {"province": "Punjab", "district": "Jhelum", "city": "Jhelum"},
    "Chakwal": {"province": "Punjab", "district": "Chakwal", "city": "Chakwal"},
    "Attock": {"province": "Punjab", "district": "Attock", "city": "Attock"},
    "Kasur": {"province": "Punjab", "district": "Kasur", "city": "Kasur"},
    "Sheikhupura": {"province": "Punjab", "district": "Sheikhupura", "city": "Sheikhupura"},
    "Bahawalpur": {"province": "Punjab", "district": "Bahawalpur", "city": "Bahawalpur"},
    "Rahim Yar Khan": {"province": "Punjab", "district": "Rahim Yar Khan", "city": "Rahim Yar Khan"},
    "Mandi Bahauddin": {"province": "Punjab", "district": "Mandi Bahauddin", "city": "Mandi Bahauddin"},
    "Sargodha": {"province": "Punjab", "district": "Sargodha", "city": "Sargodha"},
    "Dera Ghazi Khan": {"province": "Punjab", "district": "Dera Ghazi Khan", "city": "Dera Ghazi Khan"},
    "Muzaffargarh": {"province": "Punjab", "district": "Muzaffargarh", "city": "Muzaffargarh"},
    "Karachi": {"province": "Sindh", "district": "Karachi", "city": "Karachi"},
    "Hyderabad": {"province": "Sindh", "district": "Hyderabad", "city": "Hyderabad"},
    "Sukkur": {"province": "Sindh", "district": "Sukkur", "city": "Sukkur"},
    "Larkana": {"province": "Sindh", "district": "Larkana", "city": "Larkana"},
    "Mirpur Khas": {"province": "Sindh", "district": "Mirpur Khas", "city": "Mirpur Khas"},
    "Nawabshah": {"province": "Sindh", "district": "Shaheed Benazirabad", "city": "Nawabshah"},
    "Peshawar": {"province": "Khyber Pakhtunkhwa", "district": "Peshawar", "city": "Peshawar"},
    "Abbottabad": {"province": "Khyber Pakhtunkhwa", "district": "Abbottabad", "city": "Abbottabad"},
    "Mardan": {"province": "Khyber Pakhtunkhwa", "district": "Mardan", "city": "Mardan"},
    "Swat": {"province": "Khyber Pakhtunkhwa", "district": "Swat", "city": "Mingora"},
    "Mansehra": {"province": "Khyber Pakhtunkhwa", "district": "Mansehra", "city": "Mansehra"},
    "Kohat": {"province": "Khyber Pakhtunkhwa", "district": "Kohat", "city": "Kohat"},
    "Dera Ismail Khan": {"province": "Khyber Pakhtunkhwa", "district": "Dera Ismail Khan", "city": "Dera Ismail Khan"},
    "Quetta": {"province": "Balochistan", "district": "Quetta", "city": "Quetta"},
    "Gwadar": {"province": "Balochistan", "district": "Gwadar", "city": "Gwadar"},
    "Khuzdar": {"province": "Balochistan", "district": "Khuzdar", "city": "Khuzdar"},
    "Turbat": {"province": "Balochistan", "district": "Kech", "city": "Turbat"},
}
